const workers=[
{id:'siti',name:'西蒂 Siti',rating:4.8,hot:true,status:'可立即上工',statusClass:'ok',country:'印尼',age:30,gender:'女',exp:2,area:'雙北',lang:'中文可溝通',care:'失智症、長期臥床者',skills:'老人照護、基本護理、中文可溝通',tags:['在台可速配','溫和有耐心','細心愛乾淨']},
{id:'maria',name:'瑪麗亞 Maria',rating:4.6,status:'目前不可',statusClass:'no',country:'菲律賓',age:29,gender:'女',exp:4,area:'台中',lang:'英文流利、中文基礎',care:'行動不便、陪伴就醫',skills:'流利英文、輪椅移位、緊急急救',tags:['流利英文','前雇主高評價']},
{id:'triana',name:'翠安娜 Triana',rating:4.9,hot:true,status:'可立即上工',statusClass:'ok',country:'印尼',age:41,gender:'女',exp:10,area:'全台',lang:'中文流利、台語聽得懂',care:'重度失能、重病照護',skills:'抽痰、翻身拍背、略懂台語',tags:['10年以上資歷','會聽台語','會煮台菜','具醫療護理背景']},
{id:'nguyen',name:'阿梅 Nguyen Thi Ma',rating:4.5,status:'資料審核中',statusClass:'review',country:'越南',age:35,gender:'女',exp:6,area:'高雄',lang:'基本中文',care:'醫院看護、中風復健協助',skills:'復健關節活動、基本中文',tags:['作息規律','復健協助']},
{id:'ayu',name:'阿優 Ayu',rating:4.4,status:'可立即上工',statusClass:'ok',country:'印尼',age:25,gender:'女',exp:2,area:'台南',lang:'基本中文',care:'輕度失能陪伴、家事打理',skills:'測量血壓/血糖、基本台灣菜',tags:['會煮台菜','細心愛乾淨']},
{id:'dewi',name:'黛薇 Dewi',rating:4.6,status:'可立即上工',statusClass:'ok',country:'印尼',age:38,gender:'女',exp:8,area:'雙北',lang:'中文可溝通',care:'糖尿病長者照護',skills:'胰島素注射協助、傷口護理',tags:['慢性病照護','具醫療護理背景']},
{id:'jocelyn',name:'喬瑟琳 Jocelyn',rating:4.7,hot:true,status:'可立即上工',statusClass:'ok',country:'菲律賓',age:31,gender:'女',exp:5,area:'桃園',lang:'英文流利、基礎中文',care:'帕金森氏症、防跌倒照護',skills:'復健按摩、流利英文/基礎中文',tags:['流利英文','不怕寵物']},
{id:'lan',name:'小蘭 Tran Thi Lan',rating:4.3,status:'資料審核中',statusClass:'review',country:'越南',age:28,gender:'女',exp:3,area:'雙北',lang:'中文可溝通',care:'術後照顧、長者生活陪伴',skills:'營養餐點配置、家事清潔',tags:['細心愛乾淨','作息規律']},
{id:'nuru',name:'努魯 Nuru',rating:4.8,status:'可立即上工',statusClass:'ok',country:'印尼',age:34,gender:'女',exp:7,area:'南部地區',lang:'中文可溝通',care:'全癱長者照護',skills:'鼻胃管、尿袋護理、洗澡協助',tags:['力氣大/體力好','無逃跑紀錄']},
{id:'budi',name:'布迪 Budi',rating:4.9,hot:true,status:'可立即上工',statusClass:'ok',country:'印尼',age:36,gender:'男',exp:5,area:'雙北',lang:'中文可溝通',care:'男性長者重度失能',skills:'具駕照、力氣大可移位',tags:['力氣大/體力好','會開車','在台可速配']}
];
function showToast(msg){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function workerCard(w){return `<article class="worker-card" data-country="${w.country}" data-status="${w.status}" data-exp="${w.exp}"><div><div class="avatar">👤</div><span class="status ${w.statusClass}">${w.status}</span></div><div><h3>${w.name} <span class="rating">${w.hot?'🔥':''}⭐ ${w.rating}</span></h3><div class="meta">照護種類：${w.care}<br>年資：${w.exp}年　地區：${w.area}<br>國籍：${w.country}　年齡：${w.age}歲<br>技能：${w.skills}</div><div class="chips">${w.tags.map(t=>`<span class="chip">#${t}</span>`).join('')}</div></div><div class="actions"><a class="btn btn-primary" href="worker-detail.html?id=${w.id}">查看詳情</a><a class="btn btn-secondary" href="chat.html?id=${w.id}">開始交流</a></div></article>`}
function initFind(){const list=document.getElementById('workerList');if(!list)return;function render(){const q=(document.getElementById('keyword')?.value||'').trim().toLowerCase();let selected=[...document.querySelectorAll('[data-filter]:checked')].map(x=>x.value);let rows=workers.filter(w=>{const hay=(w.name+w.country+w.area+w.lang+w.care+w.skills+w.tags.join('')).toLowerCase();const qok=!q||hay.includes(q);const fok=!selected.length||selected.some(v=>hay.includes(v.toLowerCase())||w.status.includes(v));return qok&&fok});list.innerHTML=rows.map(workerCard).join('')||'<div class="info-card" style="padding:24px">目前沒有符合條件的人選，請放寬篩選。</div>'}document.addEventListener('input',e=>{if(e.target.matches('#keyword,[data-filter]'))render()});render()}
function initChat(){const box=document.getElementById('messages');if(!box)return;const quick=document.querySelectorAll('[data-reply]');quick.forEach(btn=>btn.addEventListener('click',()=>{box.insertAdjacentHTML('beforeend',`<div class="bubble me">${btn.dataset.reply}</div>`);setTimeout(()=>box.insertAdjacentHTML('beforeend',`<div class="bubble worker">謝謝老闆，我可以配合。若需要，我們也可以安排視訊面談確認細節。</div>`),450);box.scrollTop=box.scrollHeight}));document.getElementById('sendBtn')?.addEventListener('click',()=>{const input=document.getElementById('chatInput');if(!input.value.trim())return;box.insertAdjacentHTML('beforeend',`<div class="bubble me">${input.value}</div>`);input.value='';showToast('已送出訊息，展示版會自動保存對話紀錄。')})}
document.addEventListener('click',e=>{if(e.target.matches('[data-locked]')){e.preventDefault();showToast('提出聘僱意向需完成文件驗證與一次交流紀錄後開放。')}});document.addEventListener('DOMContentLoaded',()=>{initFind();initChat()});
